version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates:z
    ports:
      - "8082:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
